From openjdk:8

ARG JAR_FILE=target/currency-exchange-services-0.0.1-SNAPSHOT.jar

COPY ${JAR_FILE} CurrencyExchnageServicedocker01.jar

ENTRYPOINT ["java","-jar","CurrencyExchnageServicedocker01.jar"]